### ISSUE TITLE
Examples are in weird order

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/docs.bacalhau.org#155]
![CleanShot 2023-03-07 at 13 56 09](https://user-images.githubusercontent.com/51317/223562337-cfb034ac-05ce-425f-a1ee-117f790fb159.png)

Can we order them somehow? Importance? Alpha? whatever

**Comment by fakela** [comment]
We can do Alphabet order

**Comment by walkerlj0** [comment]
I can work on this
