### ISSUE TITLE
error reproducing https://docs.bacalhau.org/demos/image-processing using zsh 

### ISSUE THREAD

**Issue by NiklasTR** [bacalhau-project/docs.bacalhau.org#22]
Hi COD team - we are currently working to use the tools extensively for scientific compute tasks within LabDAO. 

I am currently working through some examples and creating tutorials internally. I noticed that the example below throws an error in zsh (I am running hyper on an M1 Mac). 

```
bacalhau docker run \
  -v QmeZRGhe4PmjctYVSVHuEiA9oSXnqmYa4kQubSHgWbjv72:/input_images \
  -o results:/output_images \
  dpokidov/imagemagick \
  -- magick mogrify -resize 100x100 -quality 100 -path /output_images /input_images/*.jpg
``` 

The error is related to the * wildcard in the prompt: 

```
rindtorff@niklas ~ % bacalhau docker run \
  -v QmeZRGhe4PmjctYVSVHuEiA9oSXnqmYa4kQubSHgWbjv72:/input_images \
  -o results:/output_images \
  dpokidov/imagemagick \
  -- magick mogrify -resize 100x100 -quality 100 -path /output_images /input_images/*.jpg
zsh: no matches found: /input_images/*.jpg
```

**Comment by enricorotundo** [comment]
Hi @NiklasTR, thanks for reporting this! 
That's indeed zsh trying to resolve the wildcard, it's enough to wrap the path in quotes (i.e. `'/input_images/*.jpg'`)
I've just updated the demo :)
