### ISSUE TITLE
Disable/hide blog page

### ISSUE THREAD

**Issue by enricorotundo** [bacalhau-project/docs.bacalhau.org#71]
Whilst searching for a word with the Algolia search bar, it linked to results under the https://docs.bacalhau.org/blog/ page.
I believe the Blog is not needed or in use at the moment, so we shut it down / hide it for now?

**Comment by enricorotundo** [comment]
@fakela is this something you could look into?

**Comment by fakela** [comment]
Sure, I'll look into this
