### ISSUE TITLE
Broken link for Public Roadmap

### ISSUE THREAD

**Issue by wildanvin** [bacalhau-project/docs.bacalhau.org#73]
Hello,
In the docs, in the `intro.md` file at line 34, the link:
https://www.starmaps.app/roadmap/github.com/filecoin-project/bacalhau/issues/115  doesn't display a roadmap, it shows an error right now.  
I tried in 3 different browsers with the same result.

**Comment by DeveloperAlly** [comment]
@fakela could you take a look?

**Comment by fakela** [comment]
> @fakela could you take a look?

Sure, let me check the issue link on the dev repo

**Comment by fakela** [comment]
> Hello, In the docs, in the `intro.md` file at line 34, the link: https://www.starmaps.app/roadmap/github.com/filecoin-project/bacalhau/issues/115 doesn't display a roadmap, it shows an error right now. I tried in 3 different browsers with the same result.

I'll check the link to no why it's broken

**Comment by fakela** [comment]
The site is down when it comes back up, it will be okay
