### ISSUE TITLE
Formatting/Rewording of Running Genomics on bacalhau page

### ISSUE THREAD

**Issue by it09** [bacalhau-project/docs.bacalhau.org#83]
page: https://docs.bacalhau.org/examples/miscellaneous/Genomics/ 
<hub-user> with your docker hub username, If you don’t have a docker hub account [[Follow these instructions to create docker account](https://docs.docker.com/docker-id/)](https://docs.docker.com/docker-id/), and use the username of the account you created

<repo-name> This is the name of the container, you can name it anything you want

<tag> This is not required but you can use the latest tag
→ fix formatting

- Insalling bacalhau → typo and Bacalhau
- Where it says "`Published` " → delete “”
- #VIEWING THE OUTPUTS → formatting
- **Molecular Dynamics with Bacalhau**
- formatting of sections
    
- Where it says "`Completed` "→ delete “”

**Comment by fakela** [comment]
I'll take a look at this
