### ISSUE TITLE
Move Python SDK readme to docs

### ISSUE THREAD

**Issue by fakela** [bacalhau-project/docs.bacalhau.org#95]
@enricorotundo can I help you out on this?

**Comment by enricorotundo** [comment]
What I had in mind is:

1. Create an SDKs page in https://docs.bacalhau.org/ under the "Next steps" tab, liking the example below 👇 and to the code repository
1. Create a step-by-step example (in a notebook) to showcase the SDK
1. Simplify the [Example Use in the main Readme](https://github.com/filecoin-project/bacalhau/tree/main/python#example-use), only show the code snippet and link to the example above ☝️ 

I'd love to do (2) and (3), and leave the https://docs.bacalhau.org/ part to you. Do you think it sounds good to you?

**Comment by fakela** [comment]
> What I had in mind is:
> 
> 1. Create an SDKs page in https://docs.bacalhau.org/ under the "Next steps" tab, liking the example below 👇 and to the code repository
> 2. Create a step-by-step example (in a notebook) to showcase the SDK
> 3. Simplify the [Example Use in the main Readme](https://github.com/filecoin-project/bacalhau/tree/main/python#example-use), only show the code snippet and link to the example above ☝️
> 
> I'd love to do (2) and (3), and leave the https://docs.bacalhau.org/ part to you. Do you think it sounds good to you?

Yeah that sounds good
